### ISSUE TITLE
Не скачивает главы

### ISSUE THREAD

**Issue by dante3732** [matvikFX/mangalib-downloader#1]
При попытке скачать появляется бесконечно буква е, вероятно из-за обновления сайта.

**Comment by matvikFX** [comment]
> При попытке скачать появляется бесконечно буква е, вероятно из-за обновления сайта.

Они походу добавили новую ссылку на api, но старую не убрали, а также изменили сервер изображений на img33. 
Чтобы программа снова заработала нужно в файле client/urls.go в функции createPageURL изменить SecondURL на CompressedURL, самому собрать и не скачивать новый релиз.

**Comment by dante3732** [comment]
> > При попытке скачать появляется бесконечно буква е, вероятно из-за обновления сайта.
> 
> Они походу добавили новую ссылку на api, но старую не убрали, а также изменили сервер изображений на img33. Чтобы программа снова заработала нужно в файле client/urls.go в функции createPageURL изменить SecondURL на CompressedURL, самому собрать и не скачивать новый релиз.

Спасибо, заработало. 
Раньше была возможность скачивать главы с сайта, а недавно они обновили и теперь её можно скачивать только в кэш браузера.
